using System;

namespace AMKDownloadManager.Core.Api.DownloadManagement
{
    /// <summary>
    /// Provides download manager control handle.
    /// </summary>
    public interface IDownloadManagerHandle
    {
        IJob Job { get; }

        /// <summary>
        /// Starts download progress.
        /// </summary>
        void Start();
        /// <summary>
        /// Pause the download progress.
        /// </summary>
        void Pause();
        /// <summary>
        /// Resume the download progress if download is paused.
        /// </summary>
        void Resume();
        /// <summary>
        /// Cleans any garbage generated by application services.
        /// </summary>
        void Clean();

        void WhenFinished(Action<IDownloadManagerHandle> handle);
    }
}