#!/bin/bash

#!param $1 project path
#!param $2 package
function addReference {
    #if [ "$AMKSGEAR_LOCAL_REPOSITORY" == "" ]; then
    #    dotnet add $1 package $2
    #else
        dotnet add $1 package $2
    #fi
}

#!param $1 path
function updateReferencesToAMKsGearFx {
    dotnet remove "$1" package AMKsGear.AppLayer.Core
    dotnet remove "$1" package AMKsGear.Web.Core
    dotnet remove "$1" package AMKsGear.Core.TraceTools
    dotnet remove "$1" package AMKsGear.Core.Data
    dotnet remove "$1" package AMKsGear.Core
    dotnet remove "$1" package AMKsGear.Architecture
    
    addReference "$1" "AMKsGear.AppLayer.Core"
    addReference "$1" "AMKsGear.Web.Core"
    addReference "$1" "AMKsGear.Core.TraceTools"
    addReference "$1" "AMKsGear.Core.Data"
    addReference "$1" "AMKsGear.Core"
    addReference "$1" "AMKsGear.Architecture"
}

updateReferencesToAMKsGearFx "./AMKDownloadManager.Core/AMKDownloadManager.Core.csproj"
updateReferencesToAMKsGearFx "./AMKDownloadManager.Defaults/AMKDownloadManager.Defaults.csproj"

updateReferencesToAMKsGearFx "./AMKDownloadManager.Net/AMKDownloadManager.Net.csproj"
updateReferencesToAMKsGearFx "./AMKDownloadManager.MSTest/AMKDownloadManager.MSTest.csproj"

#updateReferencesToAMKsGearFx "./UserInterface/Misc/AMKDownloadManager.DebugMode/AMKDownloadManager.DebugMode.csproj"

#updateReferencesToAMKsGearFx "./Plugins/Misc/AMKDownloadManager.BatchDownloadFileSupport/AMKDownloadManager.BatchDownloadFileSupport.csproj"
#updateReferencesToAMKsGearFx "./Plugins/Misc/AMKDownloadManager.DebugMode/AMKDownloadManager.DebugMode.csproj"
updateReferencesToAMKsGearFx "./Plugins/Protocols/AMKDownloadManager.HttpDownloader/AMKDownloadManager.HttpDownloader.csproj"