
// This file has been generated by the GUI designer. Do not modify.
namespace AMKDownloadManager
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Button btnAddDownloadLink;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget AMKDownloadManager.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "AMKDownloadManager.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child AMKDownloadManager.MainWindow.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnAddDownloadLink = new global::Gtk.Button ();
			this.btnAddDownloadLink.CanFocus = true;
			this.btnAddDownloadLink.Name = "btnAddDownloadLink";
			this.btnAddDownloadLink.UseUnderline = true;
			this.btnAddDownloadLink.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.fixed1.Add (this.btnAddDownloadLink);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnAddDownloadLink]));
			w2.X = 107;
			w2.Y = 79;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1118;
			this.DefaultHeight = 755;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.btnAddDownloadLink.Clicked += new global::System.EventHandler (this.btnAddDownloadLink_Clicked);
		}
	}
}
